name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from conf.yml
        id: get_version
        run: |
          VERSION=$(sed -n 's/^[[:space:]]*version:[[:space:]]*//p' conf.yml | head -n 1)
          VERSION=${VERSION//\"/}
          VERSION=${VERSION//\'/}
          echo "Detected version: $VERSION"
          echo "::set-output name=VERSION::$VERSION"

      - name: Blueprint Build
        id: blueprint_build
        uses: zephrynis/blueprint-export@v1.0.0

      - name: Create Release
        id: create_release
        uses: comnoco/create-release-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: v${{ steps.get_version.outputs.VERSION }}
          body: "new version yieppie! ${{ github.event.head_commit.message }}\n\n# steps to install\n1. Drop lutheme.blueprint into your pterodactyl root folder (ts is usually /var/www/pterodactyl/)\n2. Run `blueprint -i lutheme.blueprint` in the terminal and you finished installing! :3"
          draft: false
          prerelease: false
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.blueprint_build.outputs.FILE }}
          asset_name: ${{ steps.blueprint_build.outputs.FILE }}
          tag: ${{ steps.get_version.outputs.VERSION }}
          overwrite: true
